DELETE FROM M_USER_PROFILE WHERE USER_ID=/*userId*/;

INSERT INTO M_USER_PROFILE (
	USER_ID,
	PICTURE_PATH,
	INTRODUCTION,
	SEX_KBN,
	SEX_DISCLOSE_KBN,
	BIRTHDAY,
	BIRTHDAY_DISCLOSE_KBN,
	HOME_PREFECTURE_KBN,
	HOME_PREFECTURE_DISCLOSE_KBN,
	NINKATSU_STYLE_KBN,
	NINKATSU_STYLE_DISCLOSE_KBN,
	TROUBLE_KBN,
	TROUBLE_DISCLOSE_KBN,
	TROUBLE_OTHER,
	RYUZAN_KBN,
	RYUZAN_OTHER,
	RYUZAN_DISCLOSE_KBN,
	HUSBAND_FUNIN_KBN,
	HUSBAND_FUNIN_DISCLOSE_KBN,
	HUSBAND_FUNIN_OTHER
) VALUES (
	/*userId*/,
	/*picturePath*/,
	/*introduction*/,
	/*sexKbn*/,
	/*sexDiscloseKbn*/,
	/*birthday*/,
	/*birthdayDiscloseKbn*/,
	/*homePrefectureKbn*/,
	/*homePrefectureDiscloseKbn*/,
	/*ninkatsuStyleKbnArray*/,
	/*ninkatsuStyleDiscloseKbn*/,
	/*troubleKbnArray*/,
	/*troubleDiscloseKbn*/,
	/*troubleOther*/,
	/*ryuzanKbnArray*/,
	/*ryuzanOther*/,
	/*ryuzanDiscloseKbn*/,
	/*husbandFuninKbnArray*/,
	/*husbandFuninDiscloseKbn*/,
	/*husbandFuninOther*/
);