/*
userId = $1
*/
SELECT
	MUP.USER_ID,
	MUP.NINKATSU_STYLE_KBN AS NINKATSU_STYLE_KBN_ARRAY,
	MUP.PICTURE_PATH,
	MUP.INTRODUCTION,
	MUP.SEX_KBN,
	MUP.SEX_DISCLOSE_KBN,
	MUP.BIRTHDAY,
	MUP.BIRTHDAY_DISCLOSE_KBN,
	MUP.HOME_PREFECTURE_KBN,
	MUP.HOME_PREFECTURE_DISCLOSE_KBN,
	MUP.NINKATSU_STYLE_KBN AS NINKATSU_STYLE_KBN_ARRAY,
	MUP.NINKATSU_STYLE_DISCLOSE_KBN,
	MUP.TROUBLE_KBN AS TROUBLE_KBN_ARRAY,
	MUP.TROUBLE_DISCLOSE_KBN,
	MUP.TROUBLE_OTHER,
	MUP.RYUZAN_KBN AS RYUZAN_KBN_ARRAY,
	MUP.RYUZAN_OTHER,
	MUP.RYUZAN_DISCLOSE_KBN,
	MUP.HUSBAND_FUNIN_KBN AS HUSBAND_FUNIN_KBN_ARRAY,
	MUP.HUSBAND_FUNIN_DISCLOSE_KBN,
	MUP.HUSBAND_FUNIN_OTHER
FROM M_USER_PROFILE MUP
WHERE USER_ID = /*userId*/
AND DEL_KBN = '01'